apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-controller
  labels:
    name: jenkins-controller
  namespace: default
spec:
  replicas: 1
  selector:
    name: jenkins-controller
  template:
    metadata:
      labels:
        name: jenkins-controller
    spec:
      containers:
      - name: jenkins-primary
        image: quay.io/infracloud/jenkins
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        args:
        - -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker
        volumeMounts:
        - mountPath: /var/jenkins_home/
          name: jenkins-workspace
      volumes:
      - name: jenkins-workspace
        emptyDir: {}