apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    name: jenkins-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30850
  selector:
    name: jenkins-controller