apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mongomaster
  name: mongomaster
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongomaster
        mongo_db: mongo-db
    spec:
      containers:
      - command:
        - /run.sh
        - mongod
        - --replSet
        - rs0
        - --smallfiles
        - --noprealloc
        env:
        - name: PRIMARY
          value: "true"
        image: husseingalal/mongo-k8s
        imagePullPolicy: Always
        name: mongomaster
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: mongo-ebs-primary
      restartPolicy: Always
      volumes:
      - awsElasticBlockStore:
          fsType: ext4
          volumeID: ${MONGO_PRIMARY_VOLUME_ID}
        name: mongo-ebs-primary