apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-primary
  name: mongo-primary
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo-master
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-master
spec:
  replicas: 1
  selector:
    name: mongo-master
  template:
    spec:
      containers:
      - name: mongo-master
        image: husseingalal/mongo-k8s
        ports:
        - containerPort: 27017
        env:
          - name: PRIMARY
            value: true
        volumeMounts:
        - name: mongo-ebs-primary
          mountPath: "/data/db"
          command:
            - /run.sh
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
    volumes:
        - name: mongo-ebs-primary
          awsElasticBlockStore:
      	    # Enter the volume ID below
      	    volumeID: vol-72e9e4dc
            fsType: ext4