apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: reaction-controller
  name: "reaction-controller"
  namespace: "default"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: reaction-controller
    spec:
      restartPolicy: Always
      containers:
      - image: quay.io/infracloud/reaction
        imagePullPolicy: Always
        name: "reaction-controller"
        ports:
        - containerPort: ${PORT}
        env:
        - name: ROOT_URL
          value: "http://${REACTION_ROOT_URL}:9000"
        - name: MONGO_URL
          value: mongodb://mongo-service:27017/reaction
        - name: MAIL_URL
          value: ${SMTP_ADDRESS}
        - name: REACTION_USER
          value: ${REACTION_USER}
        - name: REACTION_AUTH
          value: ${REACTION_AUTH}
        - name: REACTION_EMAIL
          value: ${REACTION_EMAIL}