apiVersion: v1
kind: Service
metadata:
  name: reaction-service
  labels:
    app: reaction-controller
  namespace: default
spec:
  ports:
  - name: reactioncommerce
    port: ${PORT}
    protocol: TCP
    targetPort: ${PORT}
  selector:
    app: reaction-controller
  type: LoadBalancer