kind: ReplicationController
apiVersion: v1
metadata:
  name: mongo-rc
spec:
  replicas: 1
  selector:
    name: mongo-master
  template:
    spec:
      containers:
      - name: mongo-master
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-empty
            mountPath: /data/db
      volumes:
      - name: mongo-empty
        emptyDir: {}
    metadata:
      labels:
        secondary: "true"
        name: mongo-master
