apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: reaction-controller
  name: "reaction-controller"
  namespace: "default"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reaction-controller
    spec:
      restartPolicy: Always
      containers:
      - image: quay.io/infracloud/reaction
        imagePullPolicy: Always
        name: "reaction-controller"
        ports:
        - containerPort: ${PORT}
        env:
#        - name: ROOT_URL
#          value: "http://${HOST_IP}:30820"
        - name: MONGO_URL
          value: mongodb://mongo-service:27017/reaction
        - name: MAIL_URL
          value: "smtp://${REACTION_EMAIL}:${REACTION_AUTH}@smtp.gmail.com:587"
        - name: REACTION_USER
          value: ${REACTION_USER}
        - name: REACTION_AUTH
          value: ${REACTION_AUTH}
        - name: REACTION_EMAIL
          value: ${REACTION_EMAIL}
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}