apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ${MONGO_CONTROLLER_NAME}
  name: ${MONGO_CONTROLLER_NAME}
  namespace: "default"
spec:
  replicas: ${MONGO_REPLICAS}
  selector:
    name: ${MONGO_CONTROLLER_NAME}
  template:
    metadata:
      labels:
        name: ${MONGO_CONTROLLER_NAME}
    spec:
      restartPolicy: Always
      containers:
      - name: ${MONGO_CONTROLLER_NAME}
        image: ${MONGO_IMAGE_NAME}
        command:
        - mongod
        - --storageEngine=wiredTiger
        imagePullPolicy: Always