apiVersion: v1
kind: Service
metadata:
  name: ${REACTION_SERVICE_NAME}
  labels:
    app: ${REACTION_CONTROLLER_NAME}
  namespace: default
spec:
  ports:
  - nodePort: ${NODE_PORT}
    port: ${PORT}
    protocol: TCP
    targetPort: ${PORT}
  selector:
    app: ${REACTION_CONTROLLER_NAME}
  type: NodePort